name: sync transcribe service

on:
  push:
    branches:
      - main

jobs:
  sync_space:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: clone hf_repo
        run: git clone https://adarshwshaw:${{ secrets.HF_KEY }}@huggingface.co/spaces/adarshwshaw/transcribe_sample hf_repo

      - name: copying files
        run: cp -r transcribe_service/* hf_repo/

      - name: sync repo
        run: |
          cd hf_repo
          git add .
          git commit -m "sync ${{ github.sha }}"
          git push https://adarshwshaw:${{ secrets.HF_KEY }}@huggingface.co/spaces/adarshwshaw/transcribe_sample main

