name: sync transcribe service

on:
  push:
    branches:
      - main

jobs:
  sync_space:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Extract transcribe service
        run: |
          mkdir -p copy_transcribe_service
          cp -r transcribe_service/* copy_transcribe_service/

      - name: clone hf_repo
        uses: actions/checkout@v2
        with:
          repository: adarshwshaw/transcribe_sample
          token: ${{ secrets.HF_KEY }}
          path: hf_repo

      - run: ls 
      - run: ls hf_repo
